---
title: "Use percent"
author: "Charles Mercieca"
date: "20/02/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

tbl <- tibble(population = 350000,
       turnout = seq(0.85, 0.95, by = 0.02),
       turnout_pop = population * turnout) %>% 
  crossing(margin = seq(0.01, 0.151, by = 0.01)) %>% 
  mutate(gap = turnout_pop * margin,
         perc = paste0(turnout*100, '%'))

p = ggplot(tbl, aes(x = gap, y = margin, col = perc))+
  geom_line()+ 
  #scale_x_continuous(trans='log10', labels = scales::comma)+ 
  scale_x_continuous(labels = scales::comma, expand = c(0, NA))+ 
  scale_y_continuous(labels = scales::percent, expand = c(0, 0))+
  theme_bw()+
  theme(legend.position = c(0.9, 0.3), 
        legend.background = element_rect(fill="lightblue", 
                                         size=0.5, linetype="solid"))+
  labs(color = 'Turnout',
       title = 'Turnout impacts the gap in "votes" drastically')+
  ylab('% Margin between Parties')+
  xlab('Gap in "Votes"')
  

p + annotate("segment", x = 1, xend = 29750, y = 0.1, yend = 0.1,
           colour = "grey50", arrow = arrow(length = unit(2, "mm")))+
  annotate("segment", x = 29750, xend = 29750, y = 0.1, yend = 0,
           colour = "grey50", arrow = arrow(length = unit(2, "mm")))+
  annotate("segment", x = 1, xend = 33250, y = 0.1, yend = 0.1,
           colour = "grey50", arrow = arrow(length = unit(2, "mm")))+
  annotate("segment", x = 33250, xend = 33250, y = 0.1, yend = 0,
           colour = "grey50", arrow = arrow(length = unit(2, "mm")))
```

